In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('/root/volume/SKL2SQL/dataset/US_Accidents_March23_test.csv')

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_columns', None)
df.head()

,ID,Source,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Severity
0,A-7182628,Source1,2020-04-17 09:29:30,2020-04-17 10:29:30,26.706900,-80.119360,26.706900,-80.119360,0.000,At Haverhill Rd - Earlier accident.,...,False,False,False,True,False,Day,Day,Day,Day,1
1,A-5404588,Source1,2022-04-21 10:01:00.000000000,2022-04-21 11:44:08.000000000,38.781024,-121.265820,38.780377,-121.265815,0.045,Incident on STANFORD RANCH RD near HOUSE 6750 ...,...,False,True,False,False,False,Day,Day,Day,Day,2
2,A-156000,Source3,2016-08-12 16:45:00,2016-08-12 17:15:00,33.985249,-84.269348,NaN,NaN,0.000,Accident on GA-140 Holcomb Bridge Rd Westbound...,...,False,False,False,False,False,Day,Day,Day,Day,3
3,A-1871277,Source2,2019-09-20 15:22:16,2019-09-20 15:56:00,47.118706,-122.556908,NaN,NaN,0.000,Left lane blocked due to accident on I-5 North...,...,False,False,False,False,False,Day,Day,Day,Day,3
4,A-2031222,Source2,2019-06-03 16:55:43,2019-06-03 18:12:09,33.451355,-111.890343,NaN,NaN,0.000,Right lane closed due to accident on AZ-101-LO...,...,False,False,False,False,False,Day,Day,Day,Day,2

In [31]:
df.to_csv('/root/volume/SKL2SQL/dataset/US_Accidents_March23_test.csv', na_rep='NULL', index=False, header=False)

In [10]:
df[:100].to_csv('/root/volume/SKL2SQL/dataset/US_Accidents_March23_test_head_100_rows.csv', na_rep='NULL', index=False, header=False)

In [40]:
for i in range(len(df)):
    if not pd.isna(df.at[i, 'Description']) and df.at[i, 'Description'][-1] == '\\':
        df.at[i, 'Description'] += ' '